language: cpp
sudo: false

compiler:
  - gcc

env:
  matrix:
    - PLUS=g++ MINUS=gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

before_script:
  - export CXX=$PLUS CC=$MINUS

script: make && ./test/correctness/hashunit.exe && ./test/correctness/uniform_sanity.exe && ./test/correctness/clmulunit.exe
