language: cpp
sudo: false

compiler:
  - gcc

# We need a newer gcc for -mavx2
env:
  matrix:
    - PLUS=g++-4.8 MINUS=gcc-4.8
    - PLUS=clang++ MINUS=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export CXX=$PLUS CC=$MINUS

script: make && ./uniformsanity && ./clmulunit
